[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pinata = "BMuoaTUJx2ufxqGVBRRmhtgx2adsVBwjKwMqMgAhpw78"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
